# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
install! 'cocoapods', :deterministic_uuids => false
source 'git@gitlab.alibaba-inc.com:XIdleFish/XSpecs.git'
source 'git@gitlab.alibaba-inc.com:alipods/specs.git'
source “git@gitlab.alibaba-inc.com:alipods/specs-mirror.git”
ali_source 'alibaba-specs'
ali_source 'alibaba-specs-mirror'

target 'Runner' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Runner
  #Performance Pod
  pod "ATSDK",  '1.3.2.15'

end
